# Generated by Django 3.2.4 on 2021-06-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeacademy', '0002_delete_css'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Python',
        ),
    ]
