# Generated by Django 3.2.4 on 2021-06-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeacademy', '0004_delete_django'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Html',
        ),
    ]
