# Generated by Django 3.2.4 on 2021-06-22 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_blog_votes_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blogger',
        ),
    ]
