# Generated by Django 3.2.3 on 2021-06-01 23:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='teck_stack',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
