# Generated by Django 3.2.3 on 2021-06-01 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20210601_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='teck_stack',
            field=models.TextField(default='Python, Html5, CSS3, Bootstrap5', null=True),
        ),
    ]
